### ISSUE TITLE
Where do I have to configure pagination?

### ISSUE THREAD

**Issue by Ricardo1980** [jefflinwood/ParseQueryAdapterWithPositions#2]
Hello! I'm trying to use pagination but it crashes!

This is my code:
        mHighscoresAdapter = new HighscoresParseItemPositionQueryAdapter(this, "Score");
        mHighscoresAdapter.mParseQueryAdapter.setObjectsPerPage(10);
        mHighscoresAdapter.mParseQueryAdapter.setPaginationEnabled(true);
        mHighscoresListView.setAdapter(mHighscoresAdapter);

I suspect it is because the "Load More" cell when I move above.
The parseObject parameter is null.

What do I have to do?
Apart from that, where do I have to setup the pagination?
Thanks a lot.

**Comment by jefflinwood** [comment]
Hi,

I haven't tried it out with pagination, but it's probably missing a method or two that the ParseQueryAdapter relies on for pagination - can you repeat the error with the sample app in the project?

**Comment by Ricardo1980** [comment]
Yes.
Instead of creating 4 objects, create 12 for instance. You will see the crash the second execution, because the first execution is still creating the objects.

And change:
    public ParseItemPositionQueryAdapter(Context context,String className) {
        mParseQueryAdapter = new ContainedParseQueryAdapter(context,className);
        mContext = context;
    }

By
    public ParseItemPositionQueryAdapter(Context context,String className) {
        mParseQueryAdapter = new ContainedParseQueryAdapter(context,className);
        mParseQueryAdapter.setObjectsPerPage(2);
        mParseQueryAdapter.setPaginationEnabled(true);
        mContext = context;
    }

You will see a crash like:
01-14 00:28:49.296    7103-7103/com.jefflinwood.parseitemtableview E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.jefflinwood.parseitemtableview, PID: 7103
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.parse.ParseObject.getString(java.lang.String)' on a null object reference
            at com.jefflinwood.util.ParseItemPositionQueryAdapter.getItemView(ParseItemPositionQueryAdapter.java:97)
            at com.jefflinwood.util.ParseItemPositionQueryAdapter.getView(ParseItemPositionQueryAdapter.java:83)
            at android.widget.AbsListView.obtainView(AbsListView.java:2344)
            at android.widget.ListView.makeAndAddView(ListView.java:1864)
            at android.widget.ListView.fillDown(ListView.java:698)
            at android.widget.ListView.fillFromTop(ListView.java:759)

Probable is related to the "Load More" cell.

**Comment by jefflinwood** [comment]
Hi, thanks for the update! I haven't had a chance to look at this yet, but I will.

**Comment by Ricardo1980** [comment]
Hello!
Any update? Do you have any clue or idea where the problem is? 
Thanks a lot!

**Comment by jefflinwood** [comment]
I think you're right - the Parse code is doing a little bit of magic to support their Load More cell as the last item in the list, so the tenth item isn't an Item.

**Comment by jefflinwood** [comment]
I would recommend not using this approach with Parse's pagination, simply because they must manage their pagination with their own UI elements and so forth. I think you have to write your own pagination code, until they open source their code.
